apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: recommendation-firefox
spec:
  destination:
    namespace: tutorial
    name: recommendation
  precedence: 2
  match:
    request:
      headers:
        user-agent:
          regex: ".*Firefox.*"  
  route:
  - labels:
      version: v2
