apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: recommendation-v1-v2
spec:
  destination:
    namespace: tutorial
    name: recommendation
  precedence: 5
  route:
  - labels:
      version: v1
    weight: 50
  - labels:
      version: v2
    weight: 50
